# Generated by Django 3.2.4 on 2021-06-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_servicio')),
                ('nombre_servicio', models.CharField(max_length=50, verbose_name='servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='rut_proveedor')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre_o_razon')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
    ]
