# Generated by Django 3.2.5 on 2021-07-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210704_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='logo',
            field=models.ImageField(null=True, upload_to='proveedores'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
