# Generated by Django 3.2.5 on 2021-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210704_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='logo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(null=True, upload_to='proveedores'),
        ),
    ]
